In [19]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b = np.array([(2,3,4),(5,6,7),(6,7,8)])

In [11]:
print(b)

[[2 3 4]
 [5 6 7]
 [6 7 8]]


In [23]:
c = np.eye(10)

In [24]:
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
b.max()

8

In [26]:
b.min()

2

In [27]:
b.sum()

48

In [28]:
b.mean()

5.333333333333333

In [29]:
b.std()

1.8856180831641267